import { defineConfig, type OxlintConfig } from "oxlint";
import blankLines from "oxlint-rules/config/blank-lines";

const projectConfig: OxlintConfig = {
    plugins: ["oxc", "typescript", "unicorn", "promise", "vitest", "import", "node", "jsdoc"],
    jsPlugins: ["oxlint-rules", "oxlint-rules/blank-lines"],
    options: {
        typeAware: true,
    },
    env: {
        builtin: true,
        node: true,
    },
    ignorePatterns: ["node_modules/**"],
    rules: {
        ...blankLines.rules,
        "antislop/no-chained-type-assertions": "error",
        "antislop/no-conditional-empty-object-spread": "error",
        "antislop/no-known-value-widening": "error",
        "antislop/no-module-mocking": "error",
        "antislop/no-never-assertions": "error",
        "antislop/no-object-parameters": "error",
        "antislop/no-reflect-apply": "error",
        "antislop/no-reflect-get": "error",
        "antislop/no-shape-in-symbol-names": "error",
        "antislop/no-unknown-returns": "error",
        "antislop/no-unknown-type-aliases": "error",
        "antislop/no-unsafe-dictionary-type": "error",
        "antislop/no-widen-then-assert": "error",
        "antislop/require-safety-comment-for-type-assertion": "error",
        "@typescript-eslint/ban-ts-comment": "error",
        "@typescript-eslint/no-duplicate-enum-values": "error",
        "@typescript-eslint/no-empty-object-type": "error",
        "@typescript-eslint/no-explicit-any": "error",
        "@typescript-eslint/no-extra-non-null-assertion": "error",
        "@typescript-eslint/no-misused-new": "error",
        "@typescript-eslint/no-namespace": "error",
        "@typescript-eslint/no-non-null-asserted-optional-chain": "error",
        "@typescript-eslint/no-require-imports": "error",
        "@typescript-eslint/no-this-alias": "error",
        "@typescript-eslint/no-unnecessary-type-constraint": "error",
        "@typescript-eslint/no-unsafe-declaration-merging": "error",
        "@typescript-eslint/no-unsafe-function-type": "error",
        "@typescript-eslint/no-wrapper-object-types": "error",
        "@typescript-eslint/prefer-as-const": "error",
        "@typescript-eslint/prefer-namespace-keyword": "error",
        "@typescript-eslint/triple-slash-reference": "error",
        "default-case-last": "error",
        "default-param-last": "error",
        eqeqeq: "error",
        "import/first": "error",
        "import/no-commonjs": "error",
        "import/no-cycle": "error",
        "import/no-duplicates": "error",
        "import/no-self-import": "error",
        "jsdoc/check-property-names": "warn",
        "jsdoc/check-tag-names": "warn",
        "jsdoc/no-defaults": "warn",
        "node/no-exports-assign": "error",
        "node/no-new-require": "error",
        "node/no-path-concat": "error",
        "no-array-constructor": "error",
        "no-duplicate-imports": "warn",
        "no-unreachable-loop": "error",
        "no-use-before-define": "warn",
        "no-unused-expressions": "error",
        "no-var": "error",
        "antislop/no-runtime-typeof": [
            "error",
            { allowFunctionChecks: true, allowInTypeGuards: true },
        ],
        "antislop/no-unknown-parameters": ["error", { allowInTypeGuards: true }],
        "oxc/approx-constant": "error",
        "oxc/no-accumulating-spread": "error",
        "promise/no-return-in-finally": "error",
        "typescript/consistent-return": "warn",
        "typescript/consistent-type-exports": "warn",
        "typescript/dot-notation": "error",
        "typescript/no-deprecated": "warn",
        "typescript/no-floating-promises": "error",
        "typescript/no-misused-promises": "error",
        "typescript/no-mixed-enums": "error",
        "typescript/no-unnecessary-boolean-literal-compare": "error",
        "typescript/no-unnecessary-condition": "warn",
        "typescript/no-unnecessary-qualifier": "error",
        "typescript/no-unnecessary-template-expression": "error",
        "typescript/no-unnecessary-type-arguments": "error",
        "typescript/no-unnecessary-type-assertion": "error",
        "typescript/no-unnecessary-type-conversion": "warn",
        "typescript/no-unnecessary-type-parameters": "error",
        "typescript/no-unsafe-argument": "error",
        "typescript/no-unsafe-assignment": "error",
        "typescript/no-unsafe-call": "error",
        "typescript/no-unsafe-enum-comparison": "error",
        "typescript/no-unsafe-function-type": "error",
        "typescript/no-unsafe-member-access": "error",
        "typescript/no-unsafe-return": "error",
        "typescript/no-unsafe-type-assertion": "error",
        "typescript/no-useless-default-assignment": "error",
        "typescript/non-nullable-type-assertion-style": "error",
        "typescript/only-throw-error": "error",
        "typescript/prefer-enum-initializers": "error",
        "typescript/prefer-find": "error",
        "typescript/prefer-includes": "error",
        "typescript/prefer-nullish-coalescing": "error",
        "typescript/prefer-optional-chain": "error",
        "typescript/prefer-promise-reject-errors": "error",
        "typescript/prefer-readonly": "error",
        "typescript/prefer-reduce-type-parameter": "error",
        "typescript/prefer-regexp-exec": "warn",
        "typescript/prefer-return-this-type": "error",
        "typescript/prefer-string-starts-ends-with": "error",
        "typescript/prefer-ts-expect-error": "error",
        "typescript/promise-function-async": "warn",
        "typescript/related-getter-setter-pairs": "error",
        "typescript/restrict-plus-operands": "error",
        "typescript/return-await": "error",
        "typescript/strict-boolean-expressions": "error",
        "typescript/strict-void-return": "warn",
        "typescript/switch-exhaustiveness-check": "error",
        "typescript/use-unknown-in-catch-callback-variable": "error",
        "unicorn/no-confusing-array-with": "error",
        "unicorn/no-object-as-default-parameter": "error",
        "unicorn/prefer-date-now": "error",
        "unicorn/prefer-math-trunc": "error",
    },
    overrides: [
        ...(blankLines.overrides ?? []),
        {
            files: ["**/*.ts"],
            rules: {
                "no-ternary": "error",
            },
        },
    ],
};

export default defineConfig(projectConfig);
